name: Linux GNU
# triggered events (push, pull_request) for the develop branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains multiple jobs for different operating systems
jobs:

  ubuntu_build:
    name: Ubuntu GNU Build
    # Run on ubuntu-latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository (and LFS objects)
        uses: actions/checkout@v2

      # Update
      - name: Update
        run: sudo apt-get update

      # Install OpenMPI
      - name: Install OpenMPI
        run: sudo apt-get install openmpi-bin libopenmpi-dev -y

      # Install NetCDF
      - name: Install NetCDF
        run: sudo apt-get install libnetcdf-dev -y

      # Install NetCDF-Fortran
      - name: Install NetCDF-Fortran
        run: sudo apt-get install libnetcdff-dev -y

      # Get NetCDF versions
      - name: Get NetCDF version
        run: |
          nc-config --version
          nf-config --version

      # Test debug mode
      - name: Test Shallow Water Debug
        run: |
          rm -rf build
          mkdir build
          cd build
          export CC=gcc
          export FC=gfortran
          cmake -DCMAKE_BUILD_TYPE=debug -DMPIEXEC_PREFLAGS=--oversubscribe ..
          make
          ctest --output-on-failure

      # Test release mode
      - name: Test Shallow Water Release
        run: |
          rm -rf build
          mkdir build
          cd build
          export CC=gcc
          export FC=gfortran
          cmake -DCMAKE_BUILD_TYPE=release -DMPIEXEC_PREFLAGS=--oversubscribe ..
          make
          ctest --output-on-failure
